/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTaskModal: typeof import('./src/components/AddTaskModal.vue')['default']
    NInput: typeof import('naive-ui')['NInput']
    StatsView: typeof import('./src/components/StatsView.vue')['default']
    TaskItem: typeof import('./src/components/TaskItem.vue')['default']
    TodayFocus: typeof import('./src/components/TodayFocus.vue')['default']
  }
}
